version: "3"
services:
  db:
    image: mysql:8.0-debian
    container_name: Nextflow_Database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data/:/var/lib/mysql
